### PR TITLE
Provide onDidHighlght hook

### LINKED ISSUE #12: Discussion: code change for minimap integration
Hi ! Happy new year to all.
I've had a look at how to build a minimap integration for this package, as @t9md noted elsewhere he is not a user of minimap himself.

I have something basic working, but I've had to make some modifications to quick-highlight as one of the current optimizations (highlighting only what's visible) means we would also show, in the minimap, those highlights only. In the context of minimap it kind of defeats its purpose, in my opinion.
So, I'm now creating all highlights (even invisible ones), which could affect performance negatively, especially for large files.
On the other side, there's currently two subscriptions to the editor scroll events that I can remove, so this will give a smoother experience during scroll, especially on large files.

What do you think @t9md ? Should such changes live in a fork, or could they be merged here ? I know some people do not use minimap, so if the change mentioned above sounds bad to you, I understand you'll be cautious about it.

### PR DESCRIPTION
**Pull request by t9md**
fix #12 
To create minimap plugin without mess

# Things to consider

- Performance impact by creating decoration for whole buffer
- Update spec

### CODE REVIEW

**Comment by t9md** [comment]
# ServiceProvider(=quick-highlight)

- package.json
```javascript
  "providedServices": {
    "quick-highlight": {
      "description": "quick-highlight events",
      "versions": {
        "1.0.0": "provideQuickHighlight"
      }
    }
  },
```

## ServiceConsumer: 3rd party package which use quick-highlight service

- package.json
```javascript
  "consumedServices": {
    "quick-highlight": {
      "versions": {
        "1.0.0": "consumeQuickHighlight"
      }
    }
```

- code to use service

```javascript
  consumeQuickHighlight(quickHighlightService) {
    const boundHandler = this.onChangedHighlights.bind(this)
    this.subscriptions.add(quickHighlightService.onDidChangeHighlight(boundHandler))
  },
```

**Comment by gouegd** [comment]
Hi t9md, is there any blocker on this, that I could help with ?

**Comment by t9md** [comment]
No if you agree with that I will merge it.

**Comment by gouegd** [comment]
I'm happy with the exposed service, thanks 👍
I will publish the minimap integration on apm when this is merged an published too.

**Comment by t9md** [comment]
Close in favor of #17.
And will send PR to you minimap-plugin soon.

**Pull request closed without merging**
